version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: wedding_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wedding_invitation_db
      MYSQL_USER: wedding_user
      MYSQL_PASSWORD: wedding_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    driver: local 
